### PR TITLE
compat with tink_io && php compat 

### PR DESCRIPTION
**Pull request by postite**
i made those change locally to make asys work with latest tink_io ... feel free to review ... not very confident about total compatibilty though :)

### CODE REVIEW

**Comment by kevinresol** [comment]
Could you revert all the format changes please?

**Comment by kevinresol** [comment]
And you shouldn't rename the hxml file, it is used by travix

**Comment by postite** [comment]
> Could you revert all the format changes please?

i don' t really know how to do that ...

**Comment by postite** [comment]
> And you shouldn't rename the hxml file, it is used by travix

yes my bad ... sorry

**Comment by postite** [comment]
@kevinresol  is that ok ?

**Comment by kevinresol** [comment]
I think the txt file shouldn't be checked in. Also the hxml changes should be unnecessary.  As for the cast in nodejs, I think it should be fixed upstream, see https://github.com/HaxeFoundation/haxe/issues/7549

**Comment by kevinresol** [comment]
So `untyped  __php__` doesn't work in haxe 4 or it is generating some warnings?

**Comment by postite** [comment]
lots of warnings ...

**Comment by kevinresol** [comment]
To be honest I don't like the code duplication. I think you can wrap only the `untyped __php__` expression

**Comment by kevinresol** [comment]
Thanks for your contributions, but your code is not very correct still. So I have manually merged it (with some additional stuff) see 02ff5631526c15d549c9d8564d95ddef8b316e8d & 0a0de151e58b538c020ef20ba901c21531708b86

**Comment by postite** [comment]
no problem .. thx for making those fix

**Pull request closed without merging**
